#!/usr/bin/env sh
#
# Shared helper: emit the cloud-config that a bitwarden_gcloud instance needs.
#
# Everything an instance must reapply at every boot belongs here, because on
# Container-Optimized OS /etc is a tmpfs overlay and does not survive a reboot.
# cloud-init runs on every boot and is the mechanism Google documents for this.
# Anything written directly into /etc/systemd/system will work until the first
# reboot and then silently disappear.
#
# Usage:  emit_cloud_config <disk-name> <mount-point> <reboot-time-hhmm>

emit_cloud_config() {
	_disk="$1"
	_mount="$2"
	_time="${3:-06:00}"

	cat <<EOF
#cloud-config
#
# Generated by bitwarden_gcloud utilities. Regenerate rather than hand-editing:
#   ./utilities/migrate-to-data-disk.sh --print-cloud-config
#
# COS resets /etc on every boot, so the mount and the update timer are declared
# here instead of installed onto the filesystem.

bootcmd:
# Mount the vault data disk. mkdir is required every boot: /mnt/disks is tmpfs
# and does not persist either.
- fsck.ext4 -tvy /dev/disk/by-id/google-${_disk}
- mkdir -p ${_mount}
- mount -t ext4 -o discard,defaults /dev/disk/by-id/google-${_disk} ${_mount}

write_files:
- path: /var/lib/bwgc/cos-update-reboot.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Reboot only when update-engine has staged an update that needs one.
    set -eu
    STATUS="\$(update_engine_client --status 2>/dev/null || true)"
    if [ -z "\$STATUS" ]; then
      echo "cos-update-reboot: could not query update_engine, doing nothing" >&2
      exit 0
    fi
    CURRENT_OP="\$(printf '%s\n' "\$STATUS" | sed -n 's/^CURRENT_OP=//p')"
    NEW_VERSION="\$(printf '%s\n' "\$STATUS" | sed -n 's/^NEW_VERSION=//p')"
    echo "cos-update-reboot: CURRENT_OP=\${CURRENT_OP:-unknown} NEW_VERSION=\${NEW_VERSION:-unknown}"
    if [ "\${CURRENT_OP:-}" = "UPDATE_STATUS_UPDATED_NEED_REBOOT" ]; then
      echo "cos-update-reboot: staged update \${NEW_VERSION:-unknown}, rebooting now"
      systemctl reboot
    else
      echo "cos-update-reboot: nothing staged, not rebooting"
    fi

- path: /var/lib/bwgc/rebind-containers.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Restart every container so its bind mounts resolve to the data disk.
    #
    # docker.service belongs to cos-critical.target and starts about twenty
    # seconds before cloud-init mounts ${_mount}, so containers are created while
    # that path is still empty. Docker materialises a missing bind source as a
    # directory: file mounts such as .env and the Caddyfile then fail with "not a
    # directory", and directory mounts quietly read the boot disk instead of the
    # vault. COS sets live-restore, so containers survive a daemon restart and
    # keep the stale mount; restarting each container re-resolves it.
    set -eu
    MOUNT=${_mount}
    if ! mountpoint -q "\$MOUNT"; then
      echo "rebind: \$MOUNT is not mounted, leaving containers alone" >&2
      exit 0
    fi
    IDS="\$(docker ps -aq)"
    if [ -z "\$IDS" ]; then
      echo "rebind: no containers"
      exit 0
    fi
    echo "rebind: restarting \$(printf '%s\\n' "\$IDS" | wc -l) containers against \$MOUNT"
    # shellcheck disable=SC2086
    docker restart \$IDS

- path: /etc/systemd/system/cos-update-reboot.service
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Reboot if Container-Optimized OS has a staged update
    After=update-engine.service
    Wants=update-engine.service

    [Service]
    Type=oneshot
    ExecStart=/bin/sh /var/lib/bwgc/cos-update-reboot.sh

- path: /etc/systemd/system/cos-update-reboot.timer
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Daily check for a staged Container-Optimized OS update

    [Timer]
    OnCalendar=*-*-* ${_time}:00
    Persistent=true

    [Install]
    WantedBy=timers.target

runcmd:
# runcmd is the first stage that runs after write_files, so the script exists.
- sh /var/lib/bwgc/rebind-containers.sh
- systemctl daemon-reload
- systemctl enable --now cos-update-reboot.timer
EOF
}
