#!/usr/bin/env sh
#
# Shared helper: emit the cloud-config that a bitwarden_gcloud instance needs.
#
# Everything an instance must reapply at every boot belongs here, because on
# Container-Optimized OS /etc is a tmpfs overlay and does not survive a reboot.
# cloud-init runs on every boot and is the mechanism Google documents for this.
# Anything written directly into /etc/systemd/system will work until the first
# reboot and then silently disappear.
#
# Usage:  emit_cloud_config <disk-name> <mount-point> <reboot-time-hhmm>

emit_cloud_config() {
	_disk="$1"
	_mount="$2"
	_time="${3:-06:00}"

	cat <<EOF
#cloud-config
#
# Generated by bitwarden_gcloud utilities. Regenerate rather than hand-editing:
#   ./utilities/migrate-to-data-disk.sh --print-cloud-config
#
# COS resets /etc on every boot, so the mount, the stack and the update timer
# are declared here instead of installed onto the filesystem.

bootcmd:
# Mount the vault data disk. mkdir is required every boot: /mnt/disks is tmpfs
# and does not persist either.
- fsck.ext4 -tvy /dev/disk/by-id/google-${_disk}
- mkdir -p ${_mount}
- mount -t ext4 -o discard,defaults /dev/disk/by-id/google-${_disk} ${_mount}

write_files:
- path: /var/lib/bwgc/compose.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Run docker compose against the deployment on the data disk. COS ships no
    # compose binary, so it comes from the docker:cli image.
    set -eu
    BWGC_DIR=${_mount}/bitwarden_gcloud
    exec docker run --rm \\
      -v /var/run/docker.sock:/var/run/docker.sock \\
      -v "\$BWGC_DIR:\$BWGC_DIR" \\
      -w "\$BWGC_DIR" \\
      --entrypoint docker \\
      docker:cli compose "\$@"

- path: /var/lib/bwgc/start-stack.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Bring the vault up once the data disk is mounted.
    #
    # docker.service belongs to cos-critical.target and starts about twenty
    # seconds before cloud-init mounts ${_mount}, so any container the daemon
    # starts by itself binds an empty directory on the boot disk. Setting
    # BWGC_RESTART_POLICY=no in .env keeps the daemon from starting the stack at
    # all, and this script starts it once the disk is there.
    #
    # With the default policy the stack is already running on those wrong paths
    # by the time this runs, so it is recreated rather than left alone. Docker
    # resolves a bind source when the container starts, and COS sets
    # live-restore, so nothing short of recreating the container corrects it.
    set -eu
    MOUNT=${_mount}
    if ! mountpoint -q "\$MOUNT"; then
      echo "bwgc: \$MOUNT is not mounted, refusing to start the stack" >&2
      exit 1
    fi
    if [ ! -f "\$MOUNT/bitwarden_gcloud/docker-compose.yml" ]; then
      echo "bwgc: no deployment at \$MOUNT/bitwarden_gcloud" >&2
      exit 1
    fi
    echo "bwgc: recreating the stack against \$MOUNT"
    sh /var/lib/bwgc/compose.sh down --remove-orphans
    sh /var/lib/bwgc/compose.sh up -d

- path: /var/lib/bwgc/supervise-stack.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Restart anything that has stopped. BWGC_RESTART_POLICY=no trades Docker's
    # own restart policy away to keep the daemon from starting the stack too
    # early, so this replaces it. "compose up -d" leaves running containers
    # alone and starts the rest, so it is safe to repeat.
    set -eu
    MOUNT=${_mount}
    mountpoint -q "\$MOUNT" || exit 0
    [ -f "\$MOUNT/bitwarden_gcloud/docker-compose.yml" ] || exit 0
    sh /var/lib/bwgc/compose.sh up -d

- path: /var/lib/bwgc/cos-update-reboot.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Reboot only when update-engine has staged an update that needs one.
    set -eu
    STATUS="\$(update_engine_client --status 2>/dev/null || true)"
    if [ -z "\$STATUS" ]; then
      echo "cos-update-reboot: could not query update_engine, doing nothing" >&2
      exit 0
    fi
    CURRENT_OP="\$(printf '%s\\n' "\$STATUS" | sed -n 's/^CURRENT_OP=//p')"
    NEW_VERSION="\$(printf '%s\\n' "\$STATUS" | sed -n 's/^NEW_VERSION=//p')"
    echo "cos-update-reboot: CURRENT_OP=\${CURRENT_OP:-unknown} NEW_VERSION=\${NEW_VERSION:-unknown}"
    if [ "\${CURRENT_OP:-}" = "UPDATE_STATUS_UPDATED_NEED_REBOOT" ]; then
      echo "cos-update-reboot: staged update \${NEW_VERSION:-unknown}, rebooting now"
      systemctl reboot
    else
      echo "cos-update-reboot: nothing staged, not rebooting"
    fi

# /var is mounted noexec, so every unit below hands its script to /bin/sh
# rather than executing the path. execve on /var/lib fails with 203/EXEC.
- path: /etc/profile.d/bwgc-link.sh
  permissions: "0644"
  owner: root
  content: |
    # Point ~/bitwarden_gcloud at the deployment for whoever is logging in.
    #
    # gcloud takes the ssh login name from the client machine rather than from
    # the Google account, so one instance hands out a separate home directory
    # per client, and only the login that ran the install has this symlink.
    #
    # Login shells only: ssh --command does not read /etc/profile, so
    # link-homes.sh covers the homes that already exist at boot.
    if [ -d "${_mount}/bitwarden_gcloud" ] && [ -w "\$HOME" ] && [ ! -e "\$HOME/bitwarden_gcloud" ]; then
      ln -sfn "${_mount}/bitwarden_gcloud" "\$HOME/bitwarden_gcloud" 2>/dev/null || true
    fi

- path: /var/lib/bwgc/link-homes.sh
  permissions: "0755"
  owner: root
  content: |
    #!/usr/bin/env sh
    # Symlink the deployment into every home present at boot. Homes are created
    # on first ssh, so a login that has never connected is not covered here;
    # /etc/profile.d/bwgc-link.sh catches those when they log in.
    set -u
    [ -d "${_mount}/bitwarden_gcloud" ] || exit 0
    for h in /home/*; do
      [ -d "\$h" ] || continue
      case "\$h" in */chronos) continue ;; esac
      [ -e "\$h/bitwarden_gcloud" ] && continue
      u="\$(basename "\$h")"
      ln -sfn "${_mount}/bitwarden_gcloud" "\$h/bitwarden_gcloud" 2>/dev/null || true
      chown -h "\$u:\$u" "\$h/bitwarden_gcloud" 2>/dev/null || true
    done

- path: /etc/systemd/system/bwgc.service
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Bitwarden stack on the vault data disk
    After=docker.service
    Requires=docker.service

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    ExecStart=/bin/sh /var/lib/bwgc/start-stack.sh
    ExecStop=/bin/sh /var/lib/bwgc/compose.sh stop

- path: /etc/systemd/system/bwgc-supervise.service
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Restart any bitwarden_gcloud container that has stopped
    After=bwgc.service

    [Service]
    Type=oneshot
    ExecStart=/bin/sh /var/lib/bwgc/supervise-stack.sh

- path: /etc/systemd/system/bwgc-supervise.timer
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Periodic check that the bitwarden_gcloud stack is up

    [Timer]
    OnBootSec=5min
    OnUnitActiveSec=5min

    [Install]
    WantedBy=timers.target

- path: /etc/systemd/system/cos-update-reboot.service
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Reboot if Container-Optimized OS has a staged update
    After=update-engine.service
    Wants=update-engine.service

    [Service]
    Type=oneshot
    ExecStart=/bin/sh /var/lib/bwgc/cos-update-reboot.sh

- path: /etc/systemd/system/cos-update-reboot.timer
  permissions: "0644"
  owner: root
  content: |
    [Unit]
    Description=Daily check for a staged Container-Optimized OS update

    [Timer]
    OnCalendar=*-*-* ${_time}:00
    Persistent=true

    [Install]
    WantedBy=timers.target

runcmd:
# runcmd is the first stage that runs after write_files, so the units exist by
# now. It also runs after bootcmd, so the data disk is already mounted.
- systemctl daemon-reload
- systemctl enable --now bwgc.service
- systemctl enable --now bwgc-supervise.timer
- systemctl enable --now cos-update-reboot.timer
- /bin/sh /var/lib/bwgc/link-homes.sh
EOF
}
